version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kenlo-usuarios-api:
    build:
      context: ../kenlo-usuarios-api # Caminho até o diretório do kenlo-usuarios-api
    volumes:
      - ../kenlo-usuarios-api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/kenlo-fmr"
    depends_on:
      - mongodb
      
  kenlo-chatgpt-api:
    build:
      context: ../kenlo-chatgpt-api # Caminho até o diretório do kenlo-chatgpt-api
    volumes:
      - ../kenlo-chatgpt-api:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/kenlo-fmr"
    depends_on:
      - mongodb

volumes:
  mongo-data: