version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  usuarios-api:
    build:
      context: ../usuarios-api # Caminho até o diretório do usuarios-api
    volumes:
      - ../usuarios-api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/kenlo-fmr"
    depends_on:
      - mongodb
      
  chatgpt-api:
    build:
      context: ../chatgpt-api # Caminho até o diretório do chatgpt-api
    volumes:
      - ../chatgpt-api:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/kenlo-fmr"
    depends_on:
      - mongodb

volumes:
  mongo-data: